name: ChestShopLogger
version: 0.1.0
author: Commander_Keks
website: http://www.cubelegends.de
main: de.cubelegends.chestshoplogger.ChestShopLogger
depend: [ChestShop]

commands:
  csl:
    description: ChestShopLogger command