name: ChestShopLogger
version: 0.1.4
author: Commander_Keks
website: http://www.cubelegends.de
dev-url: http://dev.bukkit.org/bukkit-plugins/chestshoplogger/
main: de.cubelegends.chestshoplogger.ChestShopLogger
depend: [ChestShop]

commands:
  shop:
    description: ChestShopLogger command
    
permissions:
  chestshoplogger.tp:
    description: Teleportation permission
  chestshoplogger.coords:
    description: Coordinates permission
  chestshoplogger.find:
    description: Find permission