name: ChestShopLogger
version: 0.1.3
author: Commander_Keks
website: http://www.cubelegends.de
dev-url: http://dev.bukkit.org/bukkit-plugins/chestshoplogger/
main: de.cubelegends.chestshoplogger.ChestShopLogger
depend: [ChestShop]

commands:
  chestshoplogger:
    description: ChestShopLogger command
    aliases: [shop, csl]