name: ChestShopLogger
version: @version@
authors: [Henning Storck, ColorizedMind, Jonas Friedmann, InteriorCamping]
website: https://frd.mn/
dev-url: https://github.com/the-lockedcraft-legacy-organization/ChestShopLogger
main: de.cubelegends.chestshoplogger.ChestShopLogger
depend: [ChestShop]
api-version: 1.16

commands:
  shop:
    description: ChestShopLogger command
    
permissions:
  chestshoplogger.tp:
    description: Teleportation permission
  chestshoplogger.coords:
    description: Coordinates permission
  chestshoplogger.find:
    description: Find permission